Revert "Bump arrow to accept LLVM 13.0 (#3402)" (#3404)
This reverts commit 98ae34cbbfa7b3cd142910aecfcc6fb868c6b9d9. This is needed because otherwise in the GPU containers the build fails with:

```
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-1/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createNewGVNPass()'
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-1/lib/libgandiva.so.500.0.0: undefined reference to `llvm::Type::getInt128Ty(llvm::LLVMContext&)'
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-1/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createTargetTransformInfoWrapperPass(llvm::TargetIRAnalysis)'
collect2: error: ld returned 1 exit status
```

due to the fact it finds the (modified?) llvm-amdgpu-13.0.0.21295.40300-52.el7.x86_64 package which is needed for the ROCm runtime.